# Generated by Django 6.0.6 on 2026-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('PUBLIEE', 'Publiée'), ('REFUSEE', 'Refusée'), ('RETIREE', 'Retirée')], default='EN_ATTENTE', max_length=20),
        ),
    ]
