# Generated by Django 6.0.6 on 2026-06-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_annonce_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='bailleur',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='annonce',
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='description',
            field=models.TextField(default='karpala'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='core.bailleur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='bien',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.bienimmobilier'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='localisation',
            field=models.CharField(max_length=255),
        ),
    ]
