# Generated by Django 6.0.6 on 2026-06-16 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_annonce_bailleur_remove_photo_annonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='bailleur',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='core.bailleur'),
            preserve_default=False,
        ),
    ]
