# Generated by Django 6.0.3 on 2026-06-17 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_annonce_bailleur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='bailleur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annonces', to='core.bailleur'),
        ),
        migrations.AlterField(
            model_name='bienimmobilier',
            name='proprietaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biens', to='core.bailleur'),
        ),
    ]
