# Generated by Django 6.0.3 on 2026-06-17 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_annonce_bailleur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='agent_createur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annonces_agence', to='core.agent'),
        ),
    ]
